version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    networks:
      - default
    ports:
      - "80:80"
    volumes:
      - /d/docker/nginx/html:/usr/share/nginx/html
      - /d/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /d/docker/nginx/conf.d:/etc/nginx/conf.d

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    networks:
      - default
    ports:
      - "3306:3306"
    volumes:
      - /d/docker/mysql/conf.d:/etc/mysql/conf.d:ro
      - /d/docker/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - /d/docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456

  redis:
    image: redis
    container_name: redis
    restart: always
    networks:
      - default
    ports:
      - "6379:6379"
